//! Catalogue loading and policy, shared by every REA surface.
//!
//! Deliberately **no Dioxus** — this crate is the pure layer, and the hook wiring
//! (a context provider, a `use_t`) differs per surface anyway. What is genuinely
//! common is the part worth having exactly once: parsing the on-disk shape,
//! applying `ev_lib::i18n::policy`.
//!
//! Each surface owns its own `messages/` and hands them over as
//! [`Catalogues`]. The dashboard's copy is operational — panel titles, portfolio
//! states — and the embed's is marketing; sharing one catalogue between them
//! would force one vocabulary onto two audiences. Sharing the *mechanism* costs
//! nothing and keeps a single definition of what "translated" means.
//!
//! The files are the same format the public site uses: `en/common.json` flat
//! `key → text`, every other locale `key → {en, t}` carrying the English it was
//! translated from. That is what lets one policy serve both halves of the stack.
//!
//! `en/common.json` is **generated** from the `t!` sites — English is authored
//! where it renders — so a surface's `examples/dump_messages.rs` writes it and
//! its `tests/catalogue.rs` refuses to let it go stale. Nothing here knows about
//! a *key*: the catalogue is the only reason this module reads English at all,
//! and it reads it from the committed file exactly as the code emitted it.

use std::collections::BTreeMap;

use ev_lib::i18n::{
	DEFAULT_LOCALE, LOCALES, Locale, Messages,
	policy::{ResolvedCatalogue, TranslatedCatalogue, TranslatedEntry, resolve_catalogue},
};
use serde::Deserialize;

/// One surface's five catalogues, baked in at compile time.
///
/// `include_str!` rather than a runtime fetch: these ship inside a wasm bundle,
/// where fetching would mean the first paint renders untranslated and then
/// reflows, and a failed fetch would mean no copy at all.
#[derive(Clone, Copy, Debug)]
pub struct Catalogues {
	pub en: &'static str,
	pub ru: &'static str,
	pub vi: &'static str,
	pub fr: &'static str,
	pub de: &'static str,
}
impl Catalogues {
	fn source(&self) -> Messages {
		serde_json::from_str(self.en).expect("messages/en/common.json is generated by `cargo run --example dump_messages`")
	}

	fn raw_for(&self, locale: Locale) -> Option<&'static str> {
		match locale {
			Locale::En => None,
			Locale::Ru => Some(self.ru),
			Locale::Vi => Some(self.vi),
			Locale::Fr => Some(self.fr),
			Locale::De => Some(self.de),
		}
	}

	/// Apply the translation policy to one locale.
	///
	/// Rule 1.2 in practice: an entry whose English source has moved is refused
	/// and the English served instead, so a stale translation cannot quietly
	/// contradict the page. This cannot fail into a blank label — every key
	/// English defines is present in the result.
	pub fn resolve(&self, locale: Locale) -> ResolvedCatalogue {
		let en = self.source();
		match self.raw_for(locale) {
			None => resolve_catalogue(DEFAULT_LOCALE, &en, &TranslatedCatalogue::new()),
			Some(raw) => {
				let parsed: BTreeMap<String, RawEntry> = serde_json::from_str(raw).unwrap_or_else(|e| panic!("the {locale} catalogue is malformed: {e}"));
				let translated: TranslatedCatalogue = parsed.into_iter().map(|(k, v)| (k, TranslatedEntry { en: v.en, t: v.t })).collect();
				resolve_catalogue(locale, &en, &translated)
			}
		}
	}

	/// Every non-English catalogue, resolved — what the drift check reports on.
	pub fn resolve_all(&self) -> Vec<ResolvedCatalogue> {
		LOCALES.into_iter().filter(|l| *l != DEFAULT_LOCALE).map(|l| self.resolve(l)).collect()
	}
}

/// The exact bytes a surface writes `messages/en/common.json` as, so its
/// `dump_messages` example and the test that checks the file cannot disagree
/// about formatting. Two-space indent and a trailing newline — the shape the
/// conductor's catalogues already have.
pub fn serialise(catalogue: &Messages) -> String {
	format!("{}\n", serde_json::to_string_pretty(catalogue).expect("a string map always serialises"))
}
/// `{"en": "...", "t": "..."}` — the wire shape.
///
/// `ev_lib` is dependency-free and so derives no serde; converting here is a
/// few lines for keeping the library parseable by anything.
#[derive(Deserialize)]
struct RawEntry {
	en: String,
	t: String,
}
